version: "3.7"

services:
  mysql:
    container_name: ddd-mysql
    image: mysql:8.2
    ports:
      - '3306:3306'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/conf.d:/etc/mysql/conf.d

  redis:
    container_name: ddd-redis
    image: redis:7.2-alpine
    restart: always
