// https://dbdiagram.io/d/wable-64888412722eb77494e48e6a
Project project_name {
  database_type: 'MySQL'
  Note: 'Description of the project'
}

Table users {
  id int [primary key]
  gender varchar
  name varchar [not null, unique]
  nickname string [not null, unique]
  birth date
  role varchar
  mbti varchar
  profile_image_url varchar
  created_at timestamp
  updated_at timestamp
}

Table user_favorites {
  id int [primary key]
  user_id int  [ref: > users.id]
  favorite_id int [ref: > favorites.id]
}

Table favorites {
  id int [primary key]
  term varchar // 관심사
  type varchar // 관심사의 종류
}

Table introductions {
  id int [primary key]
  user_id int [ref: > users.id]
  group_id int
  is_main bool [Note: "기본 프로필 설정"]
  descriptions varchar
}

Table groups {
  id int [primary key]
  name varchar // 그룹명
  owner_id int
  created_at timestamp
  updated_at timestamp
}

Table user_groups {
  id int [primary key]
  user_id int [ref: > users.id]
  group_id int [ref: > groups.id]
  position varchar
  created_at timestamp
  updated_at timestamp
}

Table cards {
  id int [primary key]
  from_user_id int [ref: > users.id]
  from_user_name varchar
  to_user_id int [ref: > users.id]
  to_user_name varchar
  group_id int [ref: > groups.id]
  type cardType
  content varchar
  is_visible bool
  created_at timestamp
  updated_at timestamp
}

enum cardType {
    "인사"
    "축하"
    "응원"
    "감사"
}


