spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123123

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.format_sql: true
        hibernate.enable_lazy_load_no_trans: true