jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  datasource:
    url: ENC(uW99qXewsVbrUfoUUmdEX9tTTTNEjd653F3igVYqDV2k+DC5CAmLCunwKlhSPWJU2d5cH9zuajvETWYo9XyOwJf7A0oR1xGWBYXOG+tJwGo=)
    username: ENC(NtYGB8d4CwhGQ9f5p/rmebVSMMoSWd863myZO0IHwa48zyBT9FtJQDOJl51lzL2b)
    password: ENC(ovaMAIknRctuozbNHwrZBf+0wZIlGs5PXjeMe+AWLYhMjUlc1UBXAp5IiEDwFIXp)
  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.format_sql: true
        hibernate.enable_lazy_load_no_trans: true

cloud:
  aws:
    credentials:
      accessKey: ENC(Ij9inu+dGlOweV/EyB4bFdiOh1ZZyDZBjDCmf6dq5h9+BrvKvZAJnTJIW1iF84WM9indqsHkKj2MAFCL/lU4WA==)
      secretKey: ENC(5risYUm8b7lp77GPGPr1FKFcalC+KICC+K3FKNwah7HyJlU+0Xj83hkOdsd5Ks1nyS5lBwR8f7ZJ8gZA7RFDBjcDwU4AwotOi95977DpXQI=)
    bucket: ENC(6cjlk56Ve3Gf4vqOf9MWk4gCHFhU5oeMXoYGN+VzLUON6Zs5wWn654EbIcXJXm87)
    region:
      static: ap-northeast-2
    stack:
      auto: false

private:
  group:
    secretKey: ENC(n5dxpP/9J3ZNCyimV+N8+gW6Edh9xFqdOatgQLIz5YpldVPlNNpJd7vEED+umZcP)
    validityMillis: ENC(8aPdvU+zDbp/VUAcQTx/L83Q5+WNwo0kA8D5bAjrY1OtbcnX+mi1fIE5l1TmYqZS)

# Prefix 설정
server:
  servlet:
    context-path: /api

  # cognito 설정
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: pphu5ge7ch41s2nhqmo1v5te8
            clientSecret: clientSecret
            scope: email
            redirect-uri: https://waggle-waggle.vercel.app
            clientName: userPoolAppClient
        provider:
          cognito:
            issuerUri: https://cognito-idp.{region}.amazonaws.com/{poolId}
            user-name-attribute: cognito:username
