spring:
  datasource:
    url: jdbc:mysql://localhost:3306/default
    username: root
    password: password
  cloud:
    aws:
      s3:
        credentials:
          accessKey: ${AWS_S3_ACCESS_KEY}
          secretKey: ${AWS_S3_SECRET_KEY}
        bucket: ${AWS_S3_BUCKET}
        bucket.url: ${AWS_S3_BUCKET_URL}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.format_sql: true
        hibernate.enable_lazy_load_no_trans: true

# Prefix 설정
server:
  servlet:
    context-path: /api
