jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  datasource:
    url: ENC(enkC5zDBhu7HLKAS1ejRw7CJFVt01tFe1ctjVx+R0CzVEhSeGE2utwJrQXQm9gmrUr7RVWm8bADXox5cXhJKE0qQyh4bDihj0WT2L+H8jQE=)
    username: ENC(bJ3RHmDfsp6MJ9v74tBIwTGDM3wXLS9cw2mKXvJc+pp3I0NjUytZs5XYFFv0GykB)
    password: ENC(9Shs096teqo8YjCjpGjd/te/Odl7xF09om99qjV6IsWBb44petABcl1sngaKt4+u)
  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.format_sql: true
        hibernate.enable_lazy_load_no_trans: true

cloud:
  aws:
    credentials:
      accessKey: ENC(Xmm07iXvC3PGbv3BpLE9URNexy9A/JzAfcgiROK3cl0KadW537FMb0jqNz50dEMGbvXixBUTVzKfbttVf3uYwg==)
      secretKey: ENC(3PDM4+K9Zx4GjJRD9YSuk41F3Go/zZ5MUHs7+jN41VISZkku381AKcnoXC3Zbvnz8ysPivcsxMteP+wlB1y1H7EQ6AAsZovBgqNmMuyzmjs=)
    bucket: ENC(be0O3eACXC5sWqEKZgjZtjAZy/uT2WTVmxgsuz9BALgWz5LCk8mny7iekw0enh/d)
    region:
      static: ap-northeast-2
    stack:
      auto: false
  private:
    group:
      secretKey: ENC(iGUPWEyRfu6vTBYdFeAa91gXWRpxAObYy9eSxZC8mlACtWTFFocdRj/ajb2BjZ//CvZXbNZkEtupSUZja4Quo5CF5Y03eauouKayLTBEwETy4w6w3WY9i0cVpT0UrpytZjsjdoWj+FwrQxgp5kcJ4w==)
      validityMillis: ENC(8aPdvU+zDbp/VUAcQTx/L83Q5+WNwo0kA8D5bAjrY1OtbcnX+mi1fIE5l1TmYqZS)

# Prefix 설정
server:
  servlet:
    context-path: /api

# cognito 설정
cognito:
  clientId: 60k5jb34qhf78mrq3mfaatvq0c
  issuerUri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_0q6Cok8uM