jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  datasource:
    url: ENC(pBxaXDo0d03Vl7uG7gBVbnitMEcnjqBC+/JlsricrLl9rvOu8bSZjpY7+wvldjrZnoYdZtIYnhdmTuIJf+PkmyNTserlgdWJT070+pAP2Yc=)
    username: ENC(2v85vg1wmDiI1ecFVm5//0V2p030+bN6A8CEMHR6LKd707ejtTZfeEPCr66QDLkR)
    password: ENC(mNbK8azHnelz3u0/LNxvcvYo8VBQd7FUGx7qIMS+Rc+7k7ortKlPf5yJSFmV75um)
  cloud:
    aws:
      s3:
        credentials:
          accessKey: ${AWS_S3_ACCESS_KEY}
          secretKey: ${AWS_S3_SECRET_KEY}
        bucket: ${AWS_S3_BUCKET}
      region:
        static: ${AWS_REGION}
      stack:
        auto: false

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.format_sql: true
        hibernate.enable_lazy_load_no_trans: true

# Prefix 설정
server:
  servlet:
    context-path: /api
