jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  datasource:
    url: ENC(uW99qXewsVbrUfoUUmdEX9tTTTNEjd653F3igVYqDV2k+DC5CAmLCunwKlhSPWJU2d5cH9zuajvETWYo9XyOwJf7A0oR1xGWBYXOG+tJwGo=)
    password: ENC(ovaMAIknRctuozbNHwrZBf+0wZIlGs5PXjeMe+AWLYhMjUlc1UBXAp5IiEDwFIXp)
    username: ENC(NtYGB8d4CwhGQ9f5p/rmebVSMMoSWd863myZO0IHwa48zyBT9FtJQDOJl51lzL2b)
  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate.format_sql: true
        hibernate.enable_lazy_load_no_trans: true

cloud:
  aws:
    credentials:
      accessKey: ENC(Ij9inu+dGlOweV/EyB4bFdiOh1ZZyDZBjDCmf6dq5h9+BrvKvZAJnTJIW1iF84WM9indqsHkKj2MAFCL/lU4WA==)
      secretKey: ENC(5risYUm8b7lp77GPGPr1FKFcalC+KICC+K3FKNwah7HyJlU+0Xj83hkOdsd5Ks1nyS5lBwR8f7ZJ8gZA7RFDBjcDwU4AwotOi95977DpXQI=)
    bucket: ENC(6cjlk56Ve3Gf4vqOf9MWk4gCHFhU5oeMXoYGN+VzLUON6Zs5wWn654EbIcXJXm87)
    region:
      static: ap-northeast-2
    stack:
      auto: false
  private:
    group:
      secretKey: ENC(J1jfnOM3OGzlos4RFISO6WMzaWo/rFvKRf/xLLZ3gQmYVzQroxqUWCHMyYtqFaVQ3HLHze/4jGRKrvOuw6xEnB+K5s567dK3nDGZIb4GD+PkbLlDSnGB864y5EYO7qNGlDAjmhfneLuZhysyC/S7Ag==)
      validityMillis: ENC(8aPdvU+zDbp/VUAcQTx/L83Q5+WNwo0kA8D5bAjrY1OtbcnX+mi1fIE5l1TmYqZS)

# Prefix 설정
server:
  servlet:
    context-path: /api

# cognito 설정
cognito:
  clientId: pphu5ge7ch41s2nhqmo1v5te8
  issuerUri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_80Se4Ok5g